
export const videosInVsc = [
 {
  id: 1,
  src: "https://www.youtube.com/embed/vI9d8lnH4dE",
  title: "¿Cómo Consumir una API | Pokémon API?",
  img: "https://yt3.googleusercontent.com/ytc/AL5GRJWR0RBnJKYQAioV5lL6phKCOgGscq9NOVrMDBXSNg=s88-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "Leonidas Esteban",
  views: "54",
  min: "Hace 15 min",
  minutes: "00:58",
  linkImg: "../images/img.png"
 },
 {
  id: 2,
  src: "https://www.youtube.com/embed/k_r5Kh4wptQ",
  title: "Los mejores atajos de teclado en Visual Studio Code",
  img: "https://yt3.googleusercontent.com/ytc/AL5GRJWR0RBnJKYQAioV5lL6phKCOgGscq9NOVrMDBXSNg=s88-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "Leonidas Esteban",
  views: "1,160",
  min: "10 Ago. 2021",
  minutes: "12:05",
  linkImg: "../images/img(1).png"
 },
 {
  id: 3,
  src: "https://www.youtube.com/embed/igpvckbxhJs",
  title: "Cómo compartir tus diseños con desarrollo",
  img: "https://yt3.ggpht.com/DrF_q703aMKKV4f7KWqlpc-r-KHnHFJ9E7PP9YqlIsISpQXjh5Sx10FpLjm1GozrtUA3tydIciA=s48-c-k-c0x00ffffff-no-rj",
  category: "Diseño UX",
  creator: "uxcristopher",
  views: "330",
  min: "10 ago. 2021",
  minutes: "26:15",
  linkImg: "../images/img(2).png"
 },
 {
  id: 4,
  src: "https://www.youtube.com/embed/g3RKFBbROjk",
  title: "La evolución del layout en CSS",
  img: "https://yt3.googleusercontent.com/ytc/AL5GRJWR0RBnJKYQAioV5lL6phKCOgGscq9NOVrMDBXSNg=s88-c-k-c0x00ffffff-no-rj",
  category: "Diseño-UX",
  creator: "Leonidas Esteban",
  views: "1,738",
  min: "20 jul. 2021",
  minutes: "11:35",
  linkImg: "../images/img(3).png"
 },
 {
  id: 5,
  src: "https://www.youtube.com/embed/KGj-5E3EG0Q",
  title: "Tipos de programadores",
  img: "https://yt3.googleusercontent.com/ytc/AL5GRJWR0RBnJKYQAioV5lL6phKCOgGscq9NOVrMDBXSNg=s88-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "Leonidas Esteban",
  views: "1.2 M de",
  min: "4 ago. 2021",
  minutes: "12:13",
  linkImg: "../images/img(4).png"
 },
 {
  id: 6,
  src: "https://www.youtube.com/embed/It407UNmYoY",
  title: "📩 Cómo diseñar correos. ¡PASO A PASO!",
  img: "https://yt3.ggpht.com/DrF_q703aMKKV4f7KWqlpc-r-KHnHFJ9E7PP9YqlIsISpQXjh5Sx10FpLjm1GozrtUA3tydIciA=s48-c-k-c0x00ffffff-no-rj",
  category: "Diseño-UX",
  creator: "uxcristopher",
  views: "330",
  min: "12 ago. 2021",
  minutes: "26:37",
  linkImg: "../images/img(5).png"
 },
 {
  id: 7,
  src: "https://www.youtube.com/embed/10Blk7gYQ38",
  title: "Crea tu portafolio y certifícate con /Proyectos",
  img: "https://yt3.ggpht.com/DrF_q703aMKKV4f7KWqlpc-r-KHnHFJ9E7PP9YqlIsISpQXjh5Sx10FpLjm1GozrtUA3tydIciA=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "uxcristopher",
  views: "1,775",
  min: "18 jul. 2021",
  minutes: "10:41",
  linkImg: "../images/img(6).png"
 },
 {
  id: 8,
  src: "https://www.youtube.com/embed/g3CbDto2zzs",
  title: "Paletas de color para tus proyectos usando Figma",
  img: "https://yt3.googleusercontent.com/ytc/AL5GRJWR0RBnJKYQAioV5lL6phKCOgGscq9NOVrMDBXSNg=s88-c-k-c0x00ffffff-no-rj",
  category: "Diseño-UX",
  creator: "Leonidas Esteban",
  views: "998",
  min: "29 jul. 2021",
  minutes: "06:31",
  linkImg: "../images/img(7).png"
 },
 {
  id: 9,
  src: "https://www.youtube.com/embed/7QqKcfOiBHU",
  title: "EURODANCE 90'S MIX",
  img: "https://yt3.ggpht.com/YM-UJx51_RH4YRRl1LobwRcVv6PSmjOFbV3G9o4qA_TyAeS-xDkeUvR7KqdG0OHEeMDHVwHv=s48-c-k-c0x00ffffff-no-rj",
  category: "Música",
  creator: "András Jámbor",
  views: "49,351",
  min: "29 dic. 2020",
  minutes: "03:80",
  linkImg: "../images/img(8).png"
 },
 {
  id: 10,
  src: "https://www.youtube.com/embed/RrH7XtKeq0M",
  title: "Vintage Culture Epic DJ Set From Ibirapuera, Brazil",
  img: "https://yt3.ggpht.com/ytc/AL5GRJWfNxCc5bt3PJg8FaK-5aFnbwmoq9yBBCHCK0lHXQ=s48-c-k-c0x00ffffff-no-rj",
  category: "Música",
  creator: "Dj Vintage",
  views: "1.4 M de",
  min: "3 ago. 2021",
  minutes: "03:10",
  linkImg: "../images/img(9).png"
 },
 {
  id: 11,
  src: "https://www.youtube.com/embed/MEzU1HvBo6Y",
  title: "Above &amp; Beyond in Guatape, Colombia for Cercle",
  img: "https://yt3.ggpht.com/ZszIINpun-8xsckIN2Tpq42jaqFnwJI37faRMFQoYNoJaigM9EdnFcr3jnBMZurRBfCC2C17=s48-c-k-c0x00ffffff-no-rj",
  category: "Música",
  creator: "Above & Beyond",
  views: "1,912,863 de",
  min: "26 marz. 2018",
  minutes: "02:40",
  linkImg: "../images/img(10).png"
 },
 {
  id: 12,
  src: "https://www.youtube.com/embed/LyCEN_zTE54",
  title: "Purple Disco Machine, Special Mix 2021. Best Songs &amp; Remixes",
  img: "https://yt3.ggpht.com/ytc/AL5GRJWEM9IhQj38axzF-OUncRTMoSrYYpRhfL8JXm_XRA=s48-c-k-c0x00ffffff-no-rj",
  category: "Música",
  creator: "Caroune",
  views: "1,912,863 de",
  min: "26 marz. 2018",
  minutes: "04:25",
  linkImg: "../images/img(11).png"
 },

 {
  id: 13,
  src: "https://www.youtube.com/embed/zGXGA1dMYu4",
  title: "Marc Anthony - Flor Pálida (Official Video)",
  img: "https://yt3.ggpht.com/BMZdois0D04kIJ8LtHR6YAddlABf80tIbmmsqyQk3x_rzN9rVQhWkKV6aXq2b9FvFrFVZxNe1SI=s48-c-k-c0x00ffffff-no-nd-rj",
  category: "Música",
  creator: "Marc Anthony",
  views: "1,6 M de",
  min: "26 ene. 2017",
  minutes: "10:16",
  linkImg: "../images/12.jpg"
 },
 {
  id: 14,
  src: "https://www.youtube.com/embed/LyCEN_zTE54",
  title: "Marc Anthony - Vivir Mi Vida (Official Video)",
  img: "https://yt3.ggpht.com/BMZdois0D04kIJ8LtHR6YAddlABf80tIbmmsqyQk3x_rzN9rVQhWkKV6aXq2b9FvFrFVZxNe1SI=s48-c-k-c0x00ffffff-no-nd-rj",
  category: "Música",
  creator: "Marc Anthony",
  views: "1,300 M de",
  min: "1 sep. 2016",
  minutes: "05:33",
  linkImg: "../images/13.jpg"
 },
 {
  id: 15,
  src: "https://www.youtube.com/embed/0f7bPPN9XdM",
  title: "SHAKIRA || BZRP Music Sessions #53 #Bizarrap #Shakira #MS53",
  img: "https://yt3.ggpht.com/LpCIFRJsrt1DyIMOytdAshCdo7iymSvLYM9E6Pyuwe056hn8UFmZ_asQdo2vzRSbrTDv8V30lQ=s48-c-k-c0x00ffffff-no-nd-rj",
  category: "Música",
  creator: "DJ WZRD",
  views: "21 M de",
  min: "5 feb. 2023",
  minutes: "04:05",
  linkImg: "../images/14.jpg"
 },
 {
  id: 16,
  src: "https://www.youtube.com/embed/jZGpkLElSu8",
  title: "KAROL G, Shakira - TQG (Official Video)",
  img: "https://yt3.ggpht.com/Js_Ip-lezgP0XmjUzTLsHPUN9HVBn1vMeYnx12ApUPVfSPSIBiZ2OEAMlXM86USsGv38PsCnfQ=s48-c-k-c0x00ffffff-no-nd-rj",
  category: "Música",
  creator: "KAROL G",
  views: "6, 4 M de",
  min: "3 marz. 2023",
  minutes: "03:50",
  linkImg: "../images/15.jpg"
 },
 {
  id: 17,
  src: "https://www.youtube.com/embed/suYCkYfyPWQ",
  title: "🎵KAROL G - PROVENZA | Becky G, Shakira, Rauw Alejandro",
  img: "https://yt3.ggpht.com/ytc/AL5GRJWEM9IhQj38axzF-OUncRTMoSrYYpRhfL8JXm_XRA=s48-c-k-c0x00ffffff-no-rj",
  category: "Música",
  creator: "KAROL G",
  views: "2, 2 M de",
  min: "13 abr. 2022",
  minutes: "02:40",
  linkImg: "../images/16.jpg"
 },
 {
  id: 18,
  src: "https://www.youtube.com/embed/4I25nV9hXGA",
  title: "Shakira, Rauw Alejandro - Te Felicito (Official Video)",
  img: "https://yt3.ggpht.com/9z8rZjFbBf2xB2nX0A24I2uVDNSEfj-rw3hkzoLwOlgp0IqmuMuTv3yvjgAN6ufP7rpQTXxPMRs=s48-c-k-c0x00ffffff-no-nd-rj",
  category: "Música",
  creator: "Shakira",
  views: "3,4 M de",
  min: "21 ene. 2023",
  minutes: "03:18",
  linkImg: "../images/17.jpg"
 },
 {
  id: 19,
  src: "https://www.youtube.com/embed/-oK6zL01fNM",
  title: "Curso HTML & CSS ( 1 / 5 ): Fundamentos HTML - jonmircha",
  img: "https://yt3.ggpht.com/cxZ0gdwcKZINPA0wcSjICgwaa_dLjwJUPcYjpUJTeDoZfB_gVumTpKCOACF9fiPHvwBvXpV6=s48-c-k-c0x00ffffff-no-rj",
  category: "Diseño-UX",
  creator: "jonmircha",
  views: "281043 de",
  min: "10 ene. 2023",
  minutes: "40:45",
  linkImg: "../images/18.jpg"
 },
{
  id: 20,
  src: "https://www.youtube.com/embed/PIHZRj99nHU",
  title: "Curso JavaScript: 4. Constantes (const) - #jonmircha",
  img: "https://yt3.ggpht.com/cxZ0gdwcKZINPA0wcSjICgwaa_dLjwJUPcYjpUJTeDoZfB_gVumTpKCOACF9fiPHvwBvXpV6=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "jonmircha",
  views: "213,555 de",
  min: "30 marz. 2021",
  minutes: "15:48",
  linkImg: "../images/19.jpg"
 },
 {
  id: 21,
  src: "https://www.youtube.com/embed/MPLN1ahXgcs?list=PLvq-jIkSeTUZ5XcUw8fJPTBKEHEKPMTKk",
  title: "Curso React: 1. Introducción - jonmircha",
  img: "https://yt3.ggpht.com/cxZ0gdwcKZINPA0wcSjICgwaa_dLjwJUPcYjpUJTeDoZfB_gVumTpKCOACF9fiPHvwBvXpV6=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "jonmircha",
  views: "1,912,863 de",
  min: "26 marz. 2018",
  minutes: "13:33",
  linkImg: "https://i.ytimg.com/vi/MPLN1ahXgcs/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAtSmj1UGBKKsX41Jxr5V9nwKpfJQ"
 },
 {
  id: 22,
  src: "https://www.youtube.com/embed/2SetvwBV-SU?list=PLvq-jIkSeTUZ6QgYYO3MwG9EMqC-KoLXA",
  title: "Curso Javascript 1",
  img: "https://yt3.ggpht.com/cxZ0gdwcKZINPA0wcSjICgwaa_dLjwJUPcYjpUJTeDoZfB_gVumTpKCOACF9fiPHvwBvXpV6=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "jonmircha",
  views: "1,912,863 de",
  min: "26 marz. 2018",
  minutes: "48:10",
  linkImg: "https://i.ytimg.com/vi/2SetvwBV-SU/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBhtLdWHnOJzjkkqm2jIy-lP0OmbA"
 },
 {
  id: 23,
  src: "https://www.youtube.com/embed/_c26Fyi7RFA?list=PLvq-jIkSeTUbpfewvbKLhHctdkgadAy-K",
  title: "Curso Figma: 1. Introducción - #jonmircha",
  img: "https://yt3.ggpht.com/cxZ0gdwcKZINPA0wcSjICgwaa_dLjwJUPcYjpUJTeDoZfB_gVumTpKCOACF9fiPHvwBvXpV6=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "jonmircha",
  views: "1,912,863 de",
  min: "26 marz. 2018",
  minutes: "12:08",
  linkImg: "https://i.ytimg.com/vi/_c26Fyi7RFA/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAJeXBzJBNPDlXk_poqmMay87oK-w"
 },
 {
  id: 24,
  src: "https://www.youtube.com/embed/gCox2CqYvto?list=PLvq-jIkSeTUY628cyd9LVbXSXi2xG9mUl",
  title: "Curso Grid CSS: (1/17) Introducción y Conceptos",
  img: "https://yt3.ggpht.com/ytc/AL5GRJWEM9IhQj38axzF-OUncRTMoSrYYpRhfL8JXm_XRA=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "jonmircha",
  views: "1,912,863 de",
  min: "26 marz. 2018",
  minutes: "14:20",
  linkImg: "https://i.ytimg.com/vi/gCox2CqYvto/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBYxbXZr6fdF1xbpyrF9RieQa1aVQ"
 },
 {
  id: 25,
  src: "https://www.youtube.com/embed/5cr3oqxkXfM",
  title: "Ruby 3.12 Clases - Parte 1. Instanciar un objeto - Atributos",
  img: "https://yt3.ggpht.com/-HrkHCR83x8EYd90KnEK5o8HXrbfp29BaImpNAxl4jB1WxUNAIibnXp2Sc1AG2C6KbgCF4ARcw=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "Discipulus τεχ",
  views: "94",
  min: "26 oct. 2022",
  minutes: "28:02",
  linkImg: "https://i.ytimg.com/vi/5cr3oqxkXfM/hqdefault.jpg?sqp=-oaymwE2CPYBEIoBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_giAAtAFigIMCAAQARhlIF8oOTAP&rs=AOn4CLC02VmsXwb3xs_EGoaq7c2B2XMcUg"
 },
 {
  id: 26,
  src: "https://www.youtube.com/embed/nyPaYf97_KU",
  title: "Primeros pasos en JavaScript",
  img: "https://yt3.ggpht.com/ytc/AL5GRJXlsAa52DJw2wdHLiPYgzxE46uQZlAskRXwFUCCdA=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "codigofacilito",
  views: "44,666 de",
  min: "14 jul. 2018",
  minutes: "23:10",
  linkImg: "../images/21.png"
 },
 {
  id: 27,
  src: "https://www.youtube.com/embed/-Td55c_HCUE",
  title: "6 consejos para iniciar en programación",
  img: "https://yt3.ggpht.com/ytc/AL5GRJXlsAa52DJw2wdHLiPYgzxE46uQZlAskRXwFUCCdA=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "codigofacilito",
  views: "2,5 M de",
  min: "1 abr. 2014",
  minutes: "15:30",
  linkImg: "../images/20.jpg"
 },
 {
  id: 28,
  src: "https://www.youtube.com/embed/fos_lLlwBSU",
  title: "Tutorial de JavaScript para principiantes | CÓMO PROGRAMAR",
  img: "https://yt3.ggpht.com/rwU607PYF9jK9QL2I85SdfCLVZJGGsxWukuF_LxD0PepnqEIrFVg3W85FOVPDmWdMN1SxyJ7Xi8=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "Platzi",
  views: "1,912,863 de",
  min: "19 marz. 2018",
  minutes: "16:40",
  linkImg: "../images/22.jpg"
 },
 {
  id: 29,
  src: "https://www.youtube.com/embed/SDv2vOIFIj8",
  title: "Tutorial de algoritmos de programación | Cursos Platzi",
  img: "https://yt3.ggpht.com/rwU607PYF9jK9QL2I85SdfCLVZJGGsxWukuF_LxD0PepnqEIrFVg3W85FOVPDmWdMN1SxyJ7Xi8=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "Platzi",
  views: "6,78 M de",
  min: "26 marz. 2018",
  minutes: "18:50",
  linkImg: "../images/23.jpg"
 },
 {
  id: 30,
  src: "https://www.youtube.com/embed/RtevrQZCdAU",
  title: "Cómo saber si la programación es para mi",
  img: "https://yt3.ggpht.com/rwU607PYF9jK9QL2I85SdfCLVZJGGsxWukuF_LxD0PepnqEIrFVg3W85FOVPDmWdMN1SxyJ7Xi8=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "Platzi",
  views: "1,342 M de",
  min: "4 jul. 2016",
  minutes: "30:40",
  linkImg: "../images/24.jpg"
 },
{
  id: 31,
  src: "https://www.youtube.com/embed/O6YT-JJZ3P8",
  title: "Entendiendo Callbacks en JavaScript",
  img: "https://yt3.ggpht.com/rwU607PYF9jK9QL2I85SdfCLVZJGGsxWukuF_LxD0PepnqEIrFVg3W85FOVPDmWdMN1SxyJ7Xi8=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "Platzi",
  views: "1,912 de",
  min: "16 may. 2019",
  minutes: "12:19",
  linkImg: "../images/25.jpg"
 },
 {
  id: 32,
  src: "https://www.youtube.com/embed/svcNcHSHjn4",
  title: "Demo Day - Bootcamp MAKAIA: Front - end 1",
  img: "https://yt3.ggpht.com/ytc/AL5GRJXSxcygIMuHaJFsR4MzaUvDxh2gx6TF-lTGS8Dg=s48-c-k-c0x00ffffff-no-rj",
  category: "Programación",
  creator: "Makaiaorg",
  views: "87",
  min: "18 ene. 2023",
  minutes: "20:23",
  linkImg: "https://i.ytimg.com/vi/svcNcHSHjn4/hq720.jpg?sqp=-oaymwE2COgCEMoBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARgTIEQofzAP&rs=AOn4CLAhMLkhHW5FJEO0NeQu7UXbeSbCEA"
 }
]
// <iframe width="668" height="376" src="https://www.youtube.com/embed/xqr7QOvU9Hk" title="Es NECESARIO cuidar tu salud MENTAL | Marian Rojas Estapé" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
